### ISSUE TITLE
Question: How is cl-quickcheck related to clickcheck?

### ISSUE THREAD

**Issue by harshrc** [mcandre/cl-quickcheck#6]
Hi, 
Could you clarify how is this repository related to:
https://github.com/darius/clickcheck

Is it a renaming that was made more easily accessible via quicklisp?

**Comment by mcandre** [comment]
Yes, I think so. At the time, I was interested in a QuickCheck-style unit testing library with modern integrations, such as hosting the source on a git repository, having an accessible QuickLisp package, and being able to select random elements from finite sequences. A handful of small patches were also merged into cl-quickcheck. I can't remember exactly which things were missing from the original clickcheck, but https://github.com/mcandre/cl-quickcheck/commit/da15860e84dc0f5b688855f1219d021cdbc9023d confirms cl-quickcheck's origin :)

If you'd like to merge any cl-quickcheck's patches back into clickcheck, be my guest. I don't actively maintain cl-quickcheck these days, so I'd be happy to deprecate cl-quickcheck in favor of clickcheck in fact.

**Comment by harshrc** [comment]
Thanks for answering!
